# Generated by Django 5.2.6 on 2026-01-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ['order'], 'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
