# Generated by Django 5.2.6 on 2025-10-29 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollment_affiliation_enrollment_airport1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='affiliation',
        ),
    ]
