# Generated by Django 5.2.6 on 2026-01-14 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_remove_enrollment_affiliation'),
        ('people', '0002_update_people_table_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='people.people'),
        ),
    ]
