# Generated by Django 5.2.6 on 2026-01-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_alter_enrollment_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='middle_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
