# Generated by Django 5.2.6 on 2026-01-30 00:49

import django.db.models.deletion
import enrollments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_enrollment_middle_name'),
        ('people', '0005_people_middle_name'),
        ('programs', '0012_program_application_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('application', 'Applied'), ('invitation', 'Invited'), ('staff', 'Staff Added')], default='application', max_length=12),
        ),
        migrations.CreateModel(
            name='ProgramInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address to send invitation. Required even if person is linked.', max_length=254)),
                ('token', models.CharField(db_index=True, default=enrollments.models.generate_invite_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional personal message to include in the invitation email.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='enrollments.enrollment')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, help_text='Link to existing person record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='people.people')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='programs.program')),
            ],
            options={
                'db_table': 'program_invitation',
            },
        ),
        migrations.CreateModel(
            name='InvitationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='enrollments.programinvitation')),
            ],
            options={
                'db_table': 'invitation_email',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='programinvitation',
            index=models.Index(fields=['program', 'email'], name='program_inv_program_be7ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='programinvitation',
            index=models.Index(fields=['status'], name='program_inv_status_62099b_idx'),
        ),
        migrations.AddConstraint(
            model_name='programinvitation',
            constraint=models.UniqueConstraint(fields=('program', 'email'), name='unique_invitation_per_program_email'),
        ),
    ]
