# Generated by Django 5.2.6 on 2026-02-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_enrollment_source_programinvitation_invitationemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='airport1',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='airport2',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
