# Generated by Django 6.0.2 on 2026-02-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_replace_airport_with_lodging_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the invitation email was sent', null=True),
        ),
    ]
