# Generated by Django 5.2.6 on 2026-02-26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_and_more'),
    ]

    operations = [
        # Add new fields
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('lecture', 'Public Lecture'),
                    ('workshop', 'Workshop'),
                    ('conference', 'Conference'),
                    ('social', 'Social Event'),
                    ('webinar', 'Webinar'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('published', 'Published'),
                    ('cancelled', 'Cancelled'),
                    ('postponed', 'Postponed'),
                ],
                db_index=True,
                default='published',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(
                default=False,
                help_text='Check if this is a virtual/online event.',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='online_url',
            field=models.URLField(
                blank=True,
                help_text='Zoom, Google Meet, or other virtual event link.',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Ticket price (leave blank if free).',
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Maximum attendees (leave blank for unlimited).',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_required',
            field=models.BooleanField(
                default=False,
                help_text='Require registration even for free events.',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Update existing fields with help_text and constraints
        migrations.AlterField(
            model_name='event',
            name='short_summary',
            field=models.TextField(
                blank=True,
                max_length=300,
                help_text='Brief description for list views (max 300 chars).',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='external_ticket_url',
            field=models.URLField(
                blank=True,
                help_text='External ticketing link (Eventbrite, etc.).',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(
                blank=True,
                max_length=120,
                help_text='State/Province',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_html',
            field=models.TextField(
                blank=True,
                help_text='Full event description (HTML allowed).',
            ),
        ),
        # Add database indexes
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start'], name='events_even_status_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'start'], name='events_even_event_t_idx'),
        ),
    ]
