# Generated by Django 6.0.2 on 2026-02-26 19:33

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_enhancements'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_status_336136_idx',
            old_name='events_even_status_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_event_t_0ad51a_idx',
            old_name='events_even_event_t_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], db_index=True, default='draft', max_length=20),
        ),
    ]
