# Generated by Django 6.0.3 on 2026-04-07 00:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_grant_code', models.CharField(blank=True, help_text='Pre-filled grant code for this activity (e.g. DMS-2425344). Users can override per entry.', max_length=50)),
                ('classification', models.CharField(choices=[('DIRECT', 'Direct'), ('INDIRECT', 'Indirect'), ('LEAVE', 'Leave'), ('UNALLOWABLE', 'Unallowable')], max_length=12)),
                ('description_hint', models.CharField(blank=True, help_text='Placeholder text shown in the description field on the weekly entry form.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Controls display order on forms and PDFs. Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PeriodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending — weeks not yet complete'), ('DESCRIBING', 'Ready — add descriptions before generating'), ('GENERATED', 'Generated')], default='PENDING', max_length=10)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('supervisor_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('employee_title_snapshot', models.CharField(blank=True, max_length=255)),
                ('employee_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Period Report',
                'verbose_name_plural': 'Period Reports',
                'ordering': ['-period__start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display label, e.g. 'March 2026' or 'Biweekly 03/08/26'.", max_length=100)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly (4 weeks — Salary)'), ('BIWEEKLY', 'Biweekly (2 weeks — Hourly)')], max_length=8)),
                ('staff_type', models.CharField(choices=[('SALARY', 'Salary'), ('HOURLY', 'Hourly')], max_length=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False, help_text='Lock prevents any further edits or submissions for this period.')),
            ],
            options={
                'verbose_name': 'Reporting Period',
                'verbose_name_plural': 'Reporting Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PeriodReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name_snapshot', models.CharField(max_length=255)),
                ('grant_code_snapshot', models.CharField(blank=True, max_length=50)),
                ('classification_snapshot', models.CharField(max_length=12)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duties_description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('period_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='timeeffort.periodreport')),
            ],
            options={
                'verbose_name': 'Period Report Line',
                'verbose_name_plural': 'Period Report Lines',
                'ordering': ['sort_order', 'activity_name_snapshot'],
            },
        ),
        migrations.AddField(
            model_name='periodreport',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='timeeffort.reportingperiod'),
        ),
        migrations.CreateModel(
            name='ReportingWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(help_text='1-indexed within the period.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('due_date', models.DateField(blank=True, help_text='Soft deadline shown to staff. Not enforced as a hard block in v1.', null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='timeeffort.reportingperiod')),
            ],
            options={
                'verbose_name': 'Reporting Week',
                'verbose_name_plural': 'Reporting Weeks',
                'ordering': ['period', 'week_number'],
                'unique_together': {('period', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='StaffTimesheetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('SALARY', 'Salary (Monthly)'), ('HOURLY', 'Hourly (Biweekly)')], max_length=6)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supervisor', models.ForeignKey(blank=True, help_text="Supervisor with first-hand knowledge of the employee's work.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Timesheet Profile',
                'verbose_name_plural': 'Staff Timesheet Profiles',
            },
        ),
        migrations.AddField(
            model_name='periodreport',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_reports', to='timeeffort.stafftimesheetprofile'),
        ),
        migrations.CreateModel(
            name='WeeklyTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=9)),
                ('zero_week_reason', models.CharField(blank=True, help_text='Required when submitting a week with zero total hours.', max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='timeeffort.stafftimesheetprofile')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='timeeffort.reportingweek')),
            ],
            options={
                'verbose_name': 'Weekly Timesheet',
                'verbose_name_plural': 'Weekly Timesheets',
                'ordering': ['week__start_date'],
                'unique_together': {('staff', 'week')},
            },
        ),
        migrations.CreateModel(
            name='PDFSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_type', models.CharField(choices=[('WEEKLY', 'Weekly Report'), ('FINAL', 'Final Period Report')], max_length=6)),
                ('file', models.FileField(upload_to='timeeffort/pdfs/%Y/%m/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(help_text='SHA-256 of the PDF file content.', max_length=64)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='timeeffort.periodreport')),
                ('timesheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdfs', to='timeeffort.weeklytimesheet')),
            ],
            options={
                'verbose_name': 'PDF Snapshot',
                'verbose_name_plural': 'PDF Snapshots',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='periodreport',
            unique_together={('staff', 'period')},
        ),
        migrations.CreateModel(
            name='WeeklyTimesheetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_code', models.CharField(blank=True, help_text="Grant code for this entry. Defaults to the activity's default grant code.", max_length=50)),
                ('hours_sun', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('hours_mon', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('hours_tue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('hours_wed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('hours_thu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('hours_fri', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('hours_sat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('description', models.TextField(blank=True, help_text='Brief note about work performed this week for this activity.')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet_lines', to='timeeffort.activity')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='timeeffort.weeklytimesheet')),
            ],
            options={
                'verbose_name': 'Timesheet Line',
                'verbose_name_plural': 'Timesheet Lines',
                'ordering': ['activity__sort_order', 'activity__name'],
                'unique_together': {('timesheet', 'activity', 'grant_code')},
            },
        ),
    ]
