# Generated by Django 6.0.3 on 2026-04-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeeffort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_grant_addon',
            field=models.BooleanField(default=False, help_text='Grant addon activities are preset rows where the staff member specifies the grant code themselves.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_preset',
            field=models.BooleanField(default=False, help_text='Preset activities appear automatically on every weekly entry form — staff cannot remove them.'),
        ),
    ]
