# Generated by Django 6.0.3 on 2026-04-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeeffort', '0002_activity_preset_grant_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingperiod',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, help_text='Submitted timesheets can be edited until this date/time. Auto-set to period end + 3 days at 2:00 PM.', null=True),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Hard lock — overrides the deadline and prevents all edits and submissions.'),
        ),
    ]
