# Generated by Django 6.0.3 on 2026-04-17 16:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeeffort', '0003_reportingperiod_submission_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'AIM Holiday',
                'verbose_name_plural': 'AIM Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='pdfsnapshot',
            name='pdf_type',
            field=models.CharField(choices=[('WEEKLY', 'Weekly Report'), ('FINAL', 'Final Period Report'), ('DIRECTOR', 'Director Period Report')], max_length=8),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='staff_type',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('HOURLY', 'Hourly'), ('DIRECTOR', 'Director')], max_length=8),
        ),
        migrations.AlterField(
            model_name='stafftimesheetprofile',
            name='staff_type',
            field=models.CharField(choices=[('SALARY', 'Salary (Monthly)'), ('HOURLY', 'Hourly (Biweekly)'), ('DIRECTOR', 'Director (Monthly)')], max_length=8),
        ),
        migrations.CreateModel(
            name='DirectorDefaultAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_grant_code', models.CharField(blank=True, help_text='e.g. DMS-2425344', max_length=50)),
                ('main_grant_pct', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5)),
                ('pct_administrative', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('pct_other_activity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('pct_sick_personal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('pct_vacation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('pct_fundraising_pr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('pct_other_unallowable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_defaults', to='timeeffort.stafftimesheetprofile')),
            ],
            options={
                'verbose_name': 'Director Default Allocation',
                'verbose_name_plural': 'Director Default Allocations',
            },
        ),
        migrations.CreateModel(
            name='DirectorPeriodSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=9)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('supervisor_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('employee_title_snapshot', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_submissions', to='timeeffort.reportingperiod')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_submissions', to='timeeffort.stafftimesheetprofile')),
            ],
            options={
                'verbose_name': 'Director Period Submission',
                'verbose_name_plural': 'Director Period Submissions',
                'ordering': ['-period__start_date'],
                'unique_together': {('staff', 'period')},
            },
        ),
        migrations.AddField(
            model_name='pdfsnapshot',
            name='director_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdfs', to='timeeffort.directorperiodsubmission'),
        ),
        migrations.CreateModel(
            name='DirectorSubmissionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DIRECT_MAIN', 'Direct — Main Grant'), ('DIRECT_EXTRA', 'Direct — Additional Grant'), ('IND_ADMIN', 'Administrative'), ('IND_OTHER', 'Other Activity'), ('IND_SICK', 'Sick or Personal Day'), ('IND_VACATION', 'Vacation'), ('IND_HOLIDAY', 'Employer Holiday'), ('IND_FUNDRAISING', 'Fundraising / PR'), ('IND_UNALLOWABLE', 'Other Unallowable Activity')], max_length=16)),
                ('grant_code', models.CharField(blank=True, max_length=50)),
                ('slot', models.PositiveSmallIntegerField(default=0, help_text='Ordering slot for extra grant rows (1–4).')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('is_locked', models.BooleanField(default=False, help_text='True for auto-calculated lines (employer holiday).')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='timeeffort.directorperiodsubmission')),
            ],
            options={
                'verbose_name': 'Director Submission Line',
                'verbose_name_plural': 'Director Submission Lines',
                'ordering': ['slot', 'category'],
            },
        ),
    ]
