# Generated by Django 6.0.3 on 2026-04-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeeffort', '0004_aimholiday_alter_pdfsnapshot_pdf_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingperiod',
            name='staff_type',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('HOURLY', 'Hourly')], max_length=8),
        ),
    ]
