# Generated by Django 6.0.3 on 2026-04-20 19:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeeffort', '0005_alter_reportingperiod_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='directordefaultallocation',
            name='extra_grant_code_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='directordefaultallocation',
            name='extra_grant_code_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='directordefaultallocation',
            name='extra_grant_code_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='directordefaultallocation',
            name='extra_grant_code_4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='directordefaultallocation',
            name='extra_grant_pct_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='directordefaultallocation',
            name='extra_grant_pct_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='directordefaultallocation',
            name='extra_grant_pct_3',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='directordefaultallocation',
            name='extra_grant_pct_4',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
