# Generated by Django 6.0.3 on 2026-04-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeeffort', '0006_director_defaults_extra_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorsubmissionline',
            name='description',
            field=models.TextField(blank=True, help_text='Duties / work performed for this line.'),
        ),
    ]
