# Generated by Django 5.2.6 on 2026-01-28 22:29

import django.db.models.deletion
import django.utils.timezone
import filer.fields.file
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0017_image__transparent'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.CharField(blank=True, help_text='Short summary for list pages. Auto-generated from body if blank.', max_length=300)),
                ('body', models.TextField(help_text='Full article content (HTML allowed)')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured articles appear in the hero section on the news page.')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text="Article won't appear until this date/time.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at', 'is_published'], name='news_newsar_publish_a54844_idx'), models.Index(fields=['is_featured', '-published_at'], name='news_newsar_is_feat_01b3c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or summary of this issue.')),
                ('issue_date', models.DateField(db_index=True, help_text='Publication date of this newsletter issue.')),
                ('volume', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('issue_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', filer.fields.image.FilerImageField(blank=True, help_text='Cover image or thumbnail for display.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_covers', to=settings.FILER_IMAGE_MODEL)),
                ('pdf_file', filer.fields.file.FilerFileField(help_text='The newsletter PDF file.', on_delete=django.db.models.deletion.PROTECT, related_name='newsletter_pdfs', to='filer.file')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['-issue_date', 'is_published'], name='news_newsle_issue_d_e02c34_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('issue_number__isnull', False), ('volume__isnull', False)), fields=('volume', 'issue_number'), name='unique_volume_issue')],
            },
        ),
    ]
