# Generated by Django 6.0.4 on 2026-04-28 20:36

import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articleimage'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageFeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.CharField(blank=True, help_text='Short summary shown on the homepage.', max_length=300)),
                ('item_type', models.CharField(choices=[('news', 'News'), ('announcement', 'Announcement'), ('event', 'Event'), ('milestone', 'Milestone')], db_index=True, default='news', max_length=20)),
                ('url', models.CharField(blank=True, help_text="Link for 'Read more'. Use /path/ for internal or https:// for external. Leave blank for no link.", max_length=500)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text="Item won't appear until this date/time.")),
                ('pin_order', models.PositiveSmallIntegerField(blank=True, help_text='Pinned items appear first, sorted by this number lowest-first. Leave blank to sort chronologically.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='Optional thumbnail image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Homepage Feed Item',
                'verbose_name_plural': 'Homepage Feed Items',
                'indexes': [models.Index(fields=['is_active', '-published_at'], name='news_homepa_is_acti_d21680_idx')],
            },
        ),
    ]
