# Generated by Django 5.2.1 on 2025-07-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_options_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-title']},
        ),
    ]
