# Generated by Django 6.0.4 on 2026-04-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_homepage_feed_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeeditem',
            name='body',
            field=models.TextField(blank=True, help_text='Optional rich-text content displayed below the excerpt on the homepage.'),
        ),
        migrations.AlterField(
            model_name='homepagefeeditem',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Short summary shown on the homepage (max 300 chars).', max_length=300),
        ),
    ]
