# Generated by Django 6.0.4 on 2026-04-28 21:38

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_homepage_feed_item_body'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeeditem',
            name='article',
            field=models.ForeignKey(blank=True, help_text="Link to an existing news article. When set, title/excerpt/image/URL below can be left blank — they will fall back to the article's own values.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_overrides', to='news.newsarticle'),
        ),
        migrations.AlterField(
            model_name='homepagefeeditem',
            name='body',
            field=models.TextField(blank=True, help_text='Optional rich-text content displayed below the excerpt. Not inherited from the linked article.'),
        ),
        migrations.AlterField(
            model_name='homepagefeeditem',
            name='excerpt',
            field=models.CharField(blank=True, help_text="Short summary shown on the homepage (max 300 chars). Falls back to linked article's excerpt.", max_length=300),
        ),
        migrations.AlterField(
            model_name='homepagefeeditem',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text="Hero image. Falls back to linked article's featured image if blank.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='homepagefeeditem',
            name='title',
            field=models.CharField(blank=True, help_text="Leave blank when an article is linked to use that article's title.", max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagefeeditem',
            name='url',
            field=models.CharField(blank=True, help_text="Link for 'Read more'. Falls back to linked article's URL. Use /path/ for internal or https:// for external.", max_length=500),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured articles automatically appear in the homepage news feed. No manual entry needed.'),
        ),
    ]
