# Generated by Django 5.0.8 on 2025-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(storage='utils.storages_backends.MediaStorage', upload_to='frg/'),
        ),
    ]
