# Generated by Django 5.2.1 on 2025-07-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frg', '0002_alter_pdffile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(storage={'default': {'BACKEND': 'utils.storages_backends.MediaStorage', 'OPTIONS': {'bucket_name': 'aim-static-storage', 'custom_domain': 'dk87yvhh7cphv.cloudfront.net'}}, 'staticfiles': {'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage', 'OPTIONS': {'bucket_name': 'aim-static-storage', 'custom_domain': 'dk87yvhh7cphv.cloudfront.net', 'location': 'static'}}}, upload_to='frg/'),
        ),
    ]
