# Generated by Django 5.2.4 on 2025-07-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frg', '0003_alter_pdffile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(storage={'default': {'BACKEND': 'storages.backends.s3.S3Storage', 'OPTIONS': {'bucket_name': 'aim-static-storage', 'custom_domain': 'dk87yvhh7cphv.cloudfront.net', 'location': 'media'}}, 'staticfiles': {'BACKEND': 'storages.backends.s3.S3Storage', 'OPTIONS': {'bucket_name': 'aim-static-storage', 'custom_domain': 'dk87yvhh7cphv.cloudfront.net', 'location': 'static'}}}, upload_to='frg/'),
        ),
    ]
