# Generated by Django 5.2.4 on 2025-07-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frg', '0006_alter_pdffile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(storage={'default': {'BACKEND': 'storages.backends.s3.S3Storage', 'OPTIONS': {'AWS_QUERYSTRING_EXPIRE': 300, 'bucket_name': 'aim-secured-storage', 'default_acl': None, 'querystring_auth': True}}, 'staticfiles': {'BACKEND': 'storages.backends.s3.S3Storage', 'OPTIONS': {'bucket_name': 'aim-static-storage', 'custom_domain': 'dk87yvhh7cphv.cloudfront.net', 'location': 'static'}}}, upload_to='frg/'),
        ),
    ]
