# Generated by Django 6.0.3 on 2026-03-12 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0016_program_parent_square_alter_program_meeting_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('WORKSHOP', 'Workshop'), ('SQUARE', 'SQuaRE'), ('VSQUARE', 'Virtual SQuaRE'), ('VWORKSHOP', 'Virtual Workshop'), ('COMMUNITY', 'Research Community'), ('GENERAL', 'General (any program)')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist Template',
                'verbose_name_plural': 'Checklist Templates',
                'ordering': ['program_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, help_text='Instructions or context for this task.')),
                ('category', models.CharField(choices=[('pre_program', 'Pre-Program'), ('during', 'During Program'), ('post_program', 'Post-Program')], default='pre_program', max_length=20)),
                ('default_days_before_start', models.IntegerField(blank=True, help_text='Negative = days before start. Positive = days after start. Blank = no auto due date.', null=True)),
                ('default_assignee_role', models.CharField(blank=True, help_text="Hint for coordinators (e.g. 'coordinator', 'finance'). Not enforced.", max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Template Item',
                'verbose_name_plural': 'Template Items',
                'ordering': ['order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ProgramChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklists', to=settings.AUTH_USER_MODEL)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='programs.program')),
                ('template_used', models.ForeignKey(blank=True, help_text='Template this checklist was generated from. Kept for audit trail.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Program Checklist',
                'verbose_name_plural': 'Program Checklists',
            },
        ),
        migrations.CreateModel(
            name='ProgramChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('pre_program', 'Pre-Program'), ('during', 'During Program'), ('post_program', 'Post-Program')], default='pre_program', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('na', 'N/A')], default='not_started', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.programchecklist')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('template_item', models.ForeignKey(blank=True, help_text='Source template item. Null if manually added by staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklists.checklisttemplateitem')),
            ],
            options={
                'verbose_name': 'Checklist Item',
                'verbose_name_plural': 'Checklist Items',
                'ordering': ['order', 'category'],
            },
        ),
    ]
