# Generated by Django 6.0.3 on 2026-03-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'ordering': ['order', 'program_type', 'name'], 'verbose_name': 'Checklist Template', 'verbose_name_plural': 'Checklist Templates'},
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
