# Generated by Django 6.0.3 on 2026-03-12 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_add_order_to_checklisttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttemplateitem',
            name='default_assignee_role',
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='default_assignee',
            field=models.ForeignKey(blank=True, help_text='Staff member to auto-assign when this template is applied to a program.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_template_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
