# Generated by Django 5.2.4 on 2025-07-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='test',
        ),
        migrations.AddField(
            model_name='participant',
            name='workshopcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
