# Generated by Django 5.2.4 on 2025-09-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_remove_participant_test_participant_workshopcode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='oldworkshop',
            index=models.Index(fields=['workshopstartdate'], name='old_worksho_Worksho_c134b2_idx'),
        ),
    ]
