# Generated by Django 5.2.7 on 2025-10-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_oldworkshop_old_worksho_worksho_c134b2_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uniqueuser',
        ),
    ]
