# Generated by Django 5.2.7 on 2025-10-14 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_people_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
        migrations.AddField(
            model_name='participant',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='workshops.people'),
        ),
        migrations.AlterField(
            model_name='oldworkshop',
            name='organizerwebpage9',
            field=models.TextField(blank=True, db_column='Organi zerWebpage9', null=True),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['workshopcode'], name='participant_worksho_da894b_idx'),
        ),
    ]
