# Generated by Django 5.2.6 on 2026-01-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_alter_participant_options_participant_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'managed': False},
        ),
    ]
