# Generated by Django 5.2.6 on 2026-01-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_alter_people_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='people',
            table=None,
        ),
    ]
