# Generated by Django 6.0.2 on 2026-02-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Volume year (e.g., 2026)')),
                ('sequence', models.PositiveIntegerField(help_text='Entry number within the year (e.g., 5 for 2026-5)')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(help_text='Comma-separated author names')),
                ('arxiv_id', models.CharField(blank=True, help_text='ArXiv ID (e.g., 2601.11912). Leave blank if using custom URL.', max_length=20)),
                ('url', models.URLField(blank=True, help_text='Custom URL if not on arXiv')),
                ('program_type', models.CharField(blank=True, choices=[('workshop', 'Workshop'), ('square', 'SQuaRE'), ('arc', 'ARC'), ('reuf', 'REUF'), ('other', 'Other')], max_length=20)),
                ('program_code', models.CharField(blank=True, help_text='Program code (e.g., 1269)', max_length=20)),
                ('aim_thanks_page', models.PositiveIntegerField(blank=True, help_text='Page number in AIM thanks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preprint',
                'verbose_name_plural': 'Preprints',
                'ordering': ['-year', '-sequence'],
                'indexes': [models.Index(fields=['-year', '-sequence'], name='preprints_p_year_932078_idx')],
                'unique_together': {('year', 'sequence')},
            },
        ),
    ]
