# Generated by Django 6.0.2 on 2026-02-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprint',
            name='arxiv_id',
            field=models.CharField(blank=True, help_text='ArXiv ID (e.g., 2601.11912 or math.AG/0601001). Leave blank if using custom URL.', max_length=30),
        ),
    ]
