# Generated by Django 5.2.1 on 2025-07-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsarticle_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
