# Generated by Django 5.2.1 on 2025-07-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_staffmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
