# Generated by Django 4.2.13 on 2024-07-23 21:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_alter_cmsplugin_id_alter_globalpagepermission_id_and_more'),
        ('core', '0004_staffmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='position',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='id',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
            preserve_default=False,
        ),
    ]
