# Generated by Django 4.2.13 on 2024-07-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_position_staffmember_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
