# Generated by Django 4.2.13 on 2024-07-23 22:54

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('core', '0007_staffmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='image',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='staff_photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
