# Generated by Django 5.0.8 on 2025-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_newsarticle_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='staffmember',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
