# Generated by Django 5.0.8 on 2025-03-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_staffmember_options_staffmember_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={},
        ),
    ]
