# Generated by Django 5.0.8 on 2025-03-31 19:17

import djangocms_text_ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_staffmember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='bio',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
    ]
