# Generated by Django 5.2.4 on 2025-07-18 22:43

import apps.reimbursements.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReimbursementForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('orcid', models.CharField(max_length=50)),
                ('mailing_address', models.TextField()),
                ('tax_status', models.CharField(choices=[('us_citizen', 'I am a US Citizen'), ('green_card', 'I have a green card'), ('visa_permit', 'Visa/Permit')], max_length=20)),
                ('green_card_copy', models.FileField(blank=True, null=True, upload_to='green_cards/', validators=[apps.reimbursements.validators.validate_file_type, apps.reimbursements.validators.validate_file_size])),
                ('visa_option', models.CharField(blank=True, max_length=2, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('visa_type', models.CharField(blank=True, max_length=50, null=True)),
                ('i94_upload', models.FileField(blank=True, null=True, upload_to='i94_docs/')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_copy', models.FileField(blank=True, null=True, upload_to='passports/', validators=[apps.reimbursements.validators.validate_file_type, apps.reimbursements.validators.validate_file_size])),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('resident_of', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_home_address', models.TextField(blank=True, null=True)),
                ('signature', models.CharField(max_length=255)),
                ('signed_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reimbursements.event')),
            ],
        ),
        migrations.CreateModel(
            name='TravelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', validators=[apps.reimbursements.validators.validate_file_type, apps.reimbursements.validators.validate_file_size])),
                ('reimbursement_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='reimbursements.reimbursementform')),
            ],
        ),
    ]
