# Generated by Django 5.2.4 on 2025-07-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementform',
            name='visa_tax_status',
            field=models.CharField(blank=True, choices=[('resident', 'I do not have a green card but I am a resident for tax purposes according to the Substantial Presence Test'), ('non_resident', 'I am (or will be while at AIM) a non-resident for U.S. Tax Purposes')], max_length=20, null=True),
        ),
    ]
