# Generated by Django 5.2.4 on 2025-07-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0002_reimbursementform_visa_tax_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursementform',
            name='i94_upload',
        ),
        migrations.AddField(
            model_name='reimbursementform',
            name='most_recent_i94',
            field=models.FileField(blank=True, null=True, upload_to='i94/'),
        ),
        migrations.AddField(
            model_name='reimbursementform',
            name='travel_history_i94',
            field=models.FileField(blank=True, null=True, upload_to='i94/'),
        ),
    ]
