# Generated by Django 5.2.4 on 2025-07-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0003_remove_reimbursementform_i94_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementform',
            name='signed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
