# Generated by Django 5.2.4 on 2025-07-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0004_alter_reimbursementform_signed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementform',
            name='signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
