# Generated by Django 5.2.6 on 2026-01-29 18:04

import apps.reimbursements.models
import django.db.models.deletion
import django_fsm
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_enrollment_middle_name'),
        ('people', '0005_people_middle_name'),
        ('reimbursements', '0005_alter_reimbursementform_signed_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('airfare', 'Airfare'), ('ground', 'Ground Transportation'), ('lodging', 'Lodging'), ('meals', 'Meals / Per Diem'), ('baggage', 'Baggage Fees'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(help_text='Brief description of the expense.', max_length=255)),
                ('date_incurred', models.DateField(help_text='Date the expense was incurred.')),
                ('amount_requested', models.DecimalField(decimal_places=2, help_text='Amount being requested for reimbursement (USD).', max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by reviewer (may be less than requested).', max_digits=10, null=True)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from reviewer about this line item.')),
            ],
            options={
                'verbose_name': 'Expense Line Item',
                'verbose_name_plural': 'Expense Line Items',
                'ordering': ['date_incurred', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '[LEGACY] Event'},
        ),
        migrations.AlterModelOptions(
            name='reimbursementform',
            options={'verbose_name': '[LEGACY] Reimbursement Form'},
        ),
        migrations.AlterModelOptions(
            name='travelexpense',
            options={'verbose_name': '[LEGACY] Travel Expense'},
        ),
        migrations.AlterField(
            model_name='reimbursementform',
            name='green_card_copy',
            field=models.FileField(blank=True, null=True, upload_to='green_cards/'),
        ),
        migrations.AlterField(
            model_name='reimbursementform',
            name='passport_copy',
            field=models.FileField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='reimbursementform',
            name='visa_tax_status',
            field=models.CharField(blank=True, choices=[('resident', 'Resident for tax purposes'), ('non_resident', 'Non-resident for U.S. Tax Purposes')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='travelexpense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='PDF, JPG, or PNG file.', upload_to=apps.reimbursements.models.receipt_upload_path)),
                ('original_filename', models.CharField(help_text='Original filename when uploaded.', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes.')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='reimbursements.expenselineitem')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', django_fsm.FSMField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('changes_needed', 'Changes Needed'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=50, protected=True)),
                ('tax_status', models.CharField(choices=[('us_citizen', 'US Citizen'), ('green_card', 'Green Card Holder'), ('visa_resident', 'Visa Holder - Resident for Tax Purposes'), ('visa_nonresident', 'Visa Holder - Non-Resident for Tax Purposes')], help_text='Tax status determines required documentation.', max_length=20)),
                ('citizenship_country', models.CharField(blank=True, help_text='Country of citizenship (visa holders only).', max_length=100)),
                ('visa_type', models.CharField(blank=True, help_text='Visa type, e.g., J-1, F-1, H-1B.', max_length=50)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('passport_copy', models.FileField(blank=True, help_text='Copy of passport photo page.', null=True, upload_to=apps.reimbursements.models.visa_document_upload_path)),
                ('us_entry_date', models.DateField(blank=True, help_text='Most recent US entry date.', null=True)),
                ('i94_document', models.FileField(blank=True, help_text='Most recent I-94 document.', null=True, upload_to=apps.reimbursements.models.visa_document_upload_path)),
                ('tax_info_snapshot', models.JSONField(blank=True, help_text='Frozen copy of tax info at submission time.', null=True)),
                ('payment_method', models.CharField(choices=[('check', 'Check (mailed)'), ('ach', 'Direct Deposit (ACH)')], default='check', max_length=10)),
                ('payment_address', models.TextField(blank=True, help_text='Mailing address for check payments.')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_routing_number', models.CharField(blank=True, max_length=9)),
                ('bank_account_number', models.CharField(blank=True, max_length=17)),
                ('bank_account_type', models.CharField(blank=True, choices=[('checking', 'Checking'), ('savings', 'Savings')], max_length=10)),
                ('payment_info_snapshot', models.JSONField(blank=True, help_text='Frozen copy of payment info at submission time.', null=True)),
                ('total_requested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all requested amounts (calculated on submit).', max_digits=10)),
                ('total_approved', models.DecimalField(blank=True, decimal_places=2, help_text='Sum of approved amounts (set on approval).', max_digits=10, null=True)),
                ('total_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount paid (may differ from approved).', max_digits=10, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Check number, wire reference, or transaction ID.', max_length=100)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('submitter_notes', models.TextField(blank=True, help_text='Notes from the submitter.')),
                ('reviewer_notes', models.TextField(blank=True, help_text='Internal notes from reviewer (not shown to submitter).')),
                ('change_request_notes', models.TextField(blank=True, help_text='Explanation of what changes are needed.')),
                ('signature', models.CharField(blank=True, help_text='Digital signature (typed name).', max_length=255)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, help_text='The program enrollment this reimbursement is for. Leave blank for staff/vendor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reimbursement_requests', to='enrollments.enrollment')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(help_text='The person being reimbursed.', on_delete=django.db.models.deletion.PROTECT, related_name='reimbursement_requests', to='people.people')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='The user who submitted this request.', on_delete=django.db.models.deletion.PROTECT, related_name='submitted_reimbursements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reimbursement Request',
                'verbose_name_plural': 'Reimbursement Requests',
                'ordering': ['-created_at'],
                'permissions': [('can_review', 'Can review reimbursement requests'), ('can_approve', 'Can approve reimbursement requests'), ('can_mark_paid', 'Can mark reimbursements as paid'), ('can_export', 'Can export reimbursement data')],
            },
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='reimbursements.reimbursementrequest'),
        ),
        migrations.AddIndex(
            model_name='reimbursementrequest',
            index=models.Index(fields=['status', '-created_at'], name='reimburseme_status_d17490_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursementrequest',
            index=models.Index(fields=['person', '-created_at'], name='reimburseme_person__299af7_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursementrequest',
            index=models.Index(fields=['submitted_by', '-created_at'], name='reimburseme_submitt_efa102_idx'),
        ),
    ]
