# Generated by Django 5.2.6 on 2026-01-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0006_new_reimbursement_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursementform',
            name='event',
        ),
        migrations.RemoveField(
            model_name='travelexpense',
            name='reimbursement_form',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='ReimbursementForm',
        ),
        migrations.DeleteModel(
            name='TravelExpense',
        ),
    ]
