# Generated by Django 5.2 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0007_remove_legacy_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselineitem',
            name='original_currency',
            field=models.CharField(
                choices=[
                    ('USD', 'USD - US Dollar'),
                    ('GBP', 'GBP - British Pound'),
                    ('EUR', 'EUR - Euro'),
                    ('CAD', 'CAD - Canadian Dollar'),
                    ('AUD', 'AUD - Australian Dollar'),
                    ('CHF', 'CHF - Swiss Franc'),
                    ('JPY', 'JPY - Japanese Yen'),
                    ('CNY', 'CNY - Chinese Yuan'),
                    ('INR', 'INR - Indian Rupee'),
                    ('MXN', 'MXN - Mexican Peso'),
                    ('KRW', 'KRW - South Korean Won'),
                    ('BRL', 'BRL - Brazilian Real'),
                    ('OTH', 'Other'),
                ],
                default='USD',
                help_text='Currency of the original expense.',
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='original_amount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Amount in original currency (if not USD).',
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='exchange_rate',
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text='Exchange rate to USD (staff enters this for non-USD expenses).',
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='added_by_staff',
            field=models.BooleanField(
                default=False,
                help_text='True if this expense was added by staff (e.g., per diem).',
            ),
        ),
    ]
