# Generated by Django 6.0.2 on 2026-02-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0008_expenselineitem_currency_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselineitem',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, help_text='Amount in USD being requested for reimbursement.', max_digits=10),
        ),
    ]
