# Generated by Django 6.0.2 on 2026-03-09 15:58

import apps.reimbursements.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0011_alter_reimbursementrequest_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='bank_account_number',
            field=apps.reimbursements.fields.EncryptedCharField(blank=True, default='', help_text='Bank account number (encrypted)', max_length=417),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='bank_routing_number',
            field=apps.reimbursements.fields.EncryptedCharField(blank=True, default='', help_text='9-digit ABA routing number (encrypted)', max_length=409),
        ),
    ]
