# Generated by Django 6.0.3 on 2026-03-16 04:16

import apps.reimbursements.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0011_alter_reimbursementrequest_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='passport_number',
            field=apps.reimbursements.fields.EncryptedCharField(blank=True, default='', max_length=50),
        ),
    ]
