# Generated by Django 5.2.6 on 2026-01-14 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('people', '0002_update_people_table_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.people'),
        ),
    ]
