# Generated by Django 4.2.13 on 2024-05-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codenumber', models.IntegerField(blank=True, null=True)),
                ('workshopcode', models.IntegerField()),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('middlenames', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('namesuffix', models.CharField(blank=True, max_length=255, null=True)),
                ('mailingaddress', models.TextField(blank=True, null=True)),
                ('emailaddress', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('homepage', models.TextField(blank=True, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('nameprefix', models.CharField(blank=True, max_length=255, null=True)),
                ('airport1', models.CharField(blank=True, max_length=255, null=True)),
                ('airport2', models.CharField(blank=True, max_length=255, null=True)),
                ('arrivalday', models.CharField(blank=True, max_length=255, null=True)),
                ('departureday', models.CharField(blank=True, max_length=255, null=True)),
                ('mrid', models.CharField(blank=True, max_length=255, null=True)),
                ('mealrestriction', models.CharField(blank=True, max_length=255, null=True)),
                ('hotelrequirement', models.CharField(blank=True, max_length=255, null=True)),
                ('travelcomments1', models.TextField(blank=True, null=True)),
                ('travelcomments2', models.TextField(blank=True, null=True)),
                ('webpagecontribution', models.TextField(blank=True, null=True)),
                ('orcid', models.CharField(blank=True, max_length=255, null=True)),
                ('acceptedoffer', models.DateTimeField(blank=True, null=True)),
                ('declinedoffer', models.DateTimeField(blank=True, null=True)),
                ('declinedreason', models.TextField(blank=True, null=True)),
                ('travelplans', models.TextField(blank=True, null=True)),
                ('travelplanstatus', models.TextField(blank=True, null=True)),
                ('funding', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.SmallIntegerField(blank=True, null=True)),
                ('ethnicity', models.SmallIntegerField(blank=True, null=True)),
                ('unused', models.TextField(blank=True, null=True)),
                ('isorganizer', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participant',
                'managed': True,
            },
        ),
    ]
