# Generated by Django 4.2.13 on 2024-05-14 23:10

from django.db import migrations


def populate_workshop_field(apps, schema_editor):
    Participant = apps.get_model("participants", "Participant")
    OldWorkshop = apps.get_model("workshops", "OldWorkshop")

    for participant in Participant.objects.all():
        # Query the corresponding OldWorkshop record based on workshopcode
        old_workshop = OldWorkshop.objects.filter(
            workshopid=participant.workshopcode
        ).first()

        # Set the workshop foreign key field
        participant.workshop = old_workshop
        participant.save()


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0002_participant_workshop"),
    ]

    operations = [migrations.RunPython(populate_workshop_field)]
