# Generated by Django 5.2.7 on 2025-10-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('preferred_name', models.TextField(blank=True, null=True)),
                ('email_address', models.TextField(blank=True, null=True, unique=True)),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('orcid_id', models.TextField(blank=True, null=True, unique=True)),
                ('home_page', models.TextField(blank=True, null=True)),
                ('math_review_id', models.TextField(blank=True, null=True)),
                ('institution', models.TextField(blank=True, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('ethnicity', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='people_peop_last_na_e7379c_idx')],
            },
        ),
    ]
