# Generated by Django 5.2.6 on 2026-01-13 19:24

from django.db import migrations


def replace_people_table(apps, schema_editor):
    """
    Replace the old 'people' table (from workshops app) with 'people_people'
    (from people app) which has the correct structure.
    """
    with schema_editor.connection.cursor() as cursor:
        # Drop the old people table (from workshops app)
        cursor.execute('DROP TABLE IF EXISTS people CASCADE;')

        # Rename people_people to people
        cursor.execute('ALTER TABLE people_people RENAME TO people;')

        # Rename the sequence as well
        cursor.execute('ALTER SEQUENCE IF EXISTS people_people_id_seq RENAME TO people_id_seq;')

        # Update the index name
        cursor.execute('ALTER INDEX IF EXISTS people_peop_last_na_e7379c_idx RENAME TO people_last_name_first_name_idx;')


def reverse_replace(apps, schema_editor):
    """Reverse migration - not really feasible, would lose data"""
    # Reversing this migration would be complex and risky
    # If needed, restore from backup
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(replace_people_table, reverse_replace),
    ]
