# Generated by Django 5.2.6 on 2026-01-14 19:33
# Modified to be state-only - the database changes were already done in 0002

from django.db import migrations


def noop(apps, schema_editor):
    """No-op: The database is already in the correct state from migration 0002."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_update_people_table_structure'),
    ]

    operations = [
        # State-only operations: Tell Django the table and index are renamed
        # but don't actually run any SQL (already done by 0002)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='people',
                    new_name='people_last_name_first_name_idx',
                    old_name='people_peop_last_na_e7379c_idx',
                ),
                migrations.AlterModelTable(
                    name='people',
                    table='people',
                ),
            ],
            database_operations=[
                # No database operations - already done in 0002
                migrations.RunPython(noop, noop),
            ],
        ),
    ]
