# Generated by Django 5.2.6 on 2026-01-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_rename_people_peop_last_na_e7379c_idx_people_last_na_584024_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='people',
            new_name='people_name_idx',
            old_name='people_last_name_first_name_idx',
        ),
    ]
