# Generated by Django 5.2.6 on 2026-01-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_rename_people_last_name_first_name_idx_people_name_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='middle_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
