# Generated by Django 5.2.7 on 2025-10-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('title_abbreviation', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('WORKSHOP', 'Workshop'), ('SQUARE', 'SQuaRE'), ('MEETING', 'Meeting'), ('VWORKSHOP', 'Virtual Workshop'), ('VSQUARE', 'Virtual SQuaRE'), ('COMMUNITY', 'Community')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('scribe', models.CharField(max_length=255)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('online', models.BooleanField(default=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'start_date'], name='programs_pr_type_0c832a_idx')],
            },
        ),
    ]
