# Generated by Django 5.2.7 on 2025-10-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
