# Generated by Django 5.2.7 on 2025-10-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='title_abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
