# Generated by Django 5.2.7 on 2025-10-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_title_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='scribe',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
