# Generated by Django 5.2.6 on 2025-10-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_program_location_alter_program_scribe'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='program',
            new_name='programs_type_a0b22c_idx',
            old_name='programs_pr_type_0c832a_idx',
        ),
        migrations.AlterModelTable(
            name='program',
            table='programs',
        ),
    ]
