# Generated by Django 5.2.6 on 2025-10-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_rename_programs_pr_type_0c832a_idx_programs_type_a0b22c_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='title_abbreviation',
            new_name='abbreviation',
        ),
    ]
