# Generated by Django 5.2.6 on 2025-10-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_rename_title_abbreviation_program_abbreviation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='program',
            new_name='program_type_afd908_idx',
            old_name='programs_type_a0b22c_idx',
        ),
        migrations.AlterModelTable(
            name='program',
            table='program',
        ),
    ]
