# Generated by Django 5.2.6 on 2025-10-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_rename_programs_type_a0b22c_idx_program_type_afd908_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='application_status',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='correspondence',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='organizer1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='organizer1email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='organizer2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='organizer3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='organizeremail2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='organizeremail3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='scribe_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='workshop_email_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='workshop_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
