# Generated by Django 5.2.6 on 2025-10-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_alter_program_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='organizer1email',
            new_name='organizeremail1',
        ),
    ]
