# Generated by Django 5.2.6 on 2025-12-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_rename_organizer1email_program_organizeremail1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='application_status',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='correspondence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='online',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='organizer1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='organizer2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='organizer3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='organizeremail2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='organizeremail3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='scribe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='scribe_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(blank=True, choices=[('WORKSHOP', 'Workshop'), ('SQUARE', 'SQuaRE'), ('MEETING', 'Meeting'), ('VWORKSHOP', 'Virtual Workshop'), ('VSQUARE', 'Virtual SQuaRE'), ('COMMUNITY', 'Community')], max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='workshop_email_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='workshop_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
