# Generated by Django 5.2.6 on 2026-01-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_alter_program_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='application_mode',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open Applications'), ('invite', 'Invite Only')], default='closed', max_length=10),
        ),
    ]
