# Generated by Django 5.2.6 on 2026-02-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_program_application_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCommunity',
            fields=[
            ],
            options={
                'verbose_name': 'Research Community',
                'verbose_name_plural': 'Research Communities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('programs.program',),
        ),
        migrations.CreateModel(
            name='SQuaRE',
            fields=[
            ],
            options={
                'verbose_name': 'SQuaRE',
                'verbose_name_plural': 'SQuaREs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('programs.program',),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('programs.program',),
        ),
    ]
