# Generated by Django 6.0.2 on 2026-02-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_researchcommunity_square_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='meeting_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Meeting'), (2, '2nd Meeting'), (3, '3rd Meeting')], help_text='For SQuaREs: which meeting (1st, 2nd, or 3rd)', null=True),
        ),
    ]
