# Generated by Django 6.0.2 on 2026-03-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_alter_program_code_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='parent_square',
            field=models.ForeignKey(blank=True, help_text='For SQuaRE meetings 2-5: link to the 1st meeting of this SQuaRE group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_meetings', to='programs.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='meeting_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Meeting'), (2, '2nd Meeting'), (3, '3rd Meeting'), (4, '4th Meeting'), (5, '5th Meeting')], help_text='For SQuaREs: which meeting (1st through 5th)', null=True),
        ),
    ]
